update_fastlane

default_platform(:ios)

platform :ios do
  desc "Define info account"
  before_all do
    ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
    ENV["FASTLANE_ITC_TEAM_NAME"]
    ENV["FASTLANE_TEAM_ID"]
    ENV["FASTLANE_USER"]
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]
    ENV["MATCH_PASSWORD"]
    ENV['MATCH_GIT_BASIC_AUTHORIZATION'] 
    match
  end



  lane :sync_match do 
    match(type: "adhoc")
    # match(type: "development")
    # match(type: "appstore")
  end 


  desc "Push a new beta build to TestFlight"
  lane :beta do
    #sync_match

    if is_ci
      create_keychain(
        name: "keychain.name",
        password: "keychain.name123",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end

    match(
      type: "adhoc",
      keychain_name: "keychain.name",
      keychain_password: "keychain.name123",
    )

    # update_code_signing_settings(
    #   use_automatic_signing: false,
    #   path: "Runner.xcodeproj",
    # )

    gym(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "ad-hoc",
      clean: true,
      output_directory: "./build",
      output_name: "app.ipa",
    ) 
    # upload_to_testflight
  end
end
