# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :deploy do
    upload_to_play_store(
      package_name: 'com.sergejivanov.telik',
      json_key: Dir.pwd + '/play-store-credentials.json',
      track: 'internal',
      release_status: 'draft',
      aab: Dir.pwd + '/../../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
