# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :bump_flutter_version do
    path = Dir.pwd + '/../../pubspec.yaml'
    fv_re = /\d+.\d+.\d+\+\d+/ 
    v_re = /\d+.\d+.\d+\+/ 
    bn_re = /\+\d+/

    ENV["TAG_VERSION"]
    s = File.read(path)
    full_version = s[fv_re]
    build_number = full_version[bn_re]
    new_build_number = (build_number[1...].to_i + 1).to_s
    s[fv_re] = (ENV['TAG_VERSION'] ? ENV['TAG_VERSION'] + '+' : full_version[v_re]) + new_build_number
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
  
  lane :deploy do
    upload_to_play_store(
      package_name: 'com.sergejivanov.telik',
      json_key: Dir.pwd + '/play-store-credentials.json',
      track: 'internal',
      release_status: 'draft',
      aab: Dir.pwd + '/../../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
