on:
  # pull_request:
  push:
    branches: [dev]
name: Push new beta builds to test
jobs:

  # build-android:
  #   name: Build Android App
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: '2.8.1'

  #     - run: flutter pub get

  #     - name: Build and sign
  #       run: | 
  #         echo "${{ secrets.STORE_FILE }}" | base64 -d > ${{ github.workspace }}/android/app/release.jks
  #         flutter build apk
  #         flutter build appbundle
  #       # run: flutter build apk --split-per-abi --build-number=$GITHUB_RUN_NUMBER
  #       env:
  #         STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  #         KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  #         KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  #         STORE_FILE: release.jks

  #     - name: Create play store credentials
  #       id: create-json
  #       uses: jsdaniell/create-json@1.1.2
  #       with:
  #         name: "play-store-credentials.json"
  #         json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  #         dir: 'android/fastlane/'

  #     - name: Upload appbundle to the Google play
  #       uses: maierj/fastlane-action@v2.0.1
  #       with:
  #         lane: 'deploy'
  #         subdirectory: 'android'

  build-ios:        
    name: Build iOS App
    runs-on: macos-latest
    env:
      CI: ${{ secrets.CI }}
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      FASTLANE_ITC_TEAM_NAME: ${{ secrets.FASTLANE_ITC_TEAM_NAME }}
      FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
      FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          
      - run: flutter pub get

      - name: Build
        run: |
          flutter build ios --release --no-codesign
        # run: flutter build ios --release --no-codesign --build-number=$GITHUB_RUN_NUMBER

      - name: Define a basic authorization for match
        run: |
          echo "MATCH_GIT_BASIC_AUTHORIZATION=$(echo -n '${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}' | base64)" >> $GITHUB_ENV 
      
      - name: Beta
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'beta'
          subdirectory: 'ios'

      # - name: Deploy
      #   uses: maierj/fastlane-action@v2.0.1
      #   with:
      #     lane: 'deploy'
      #     subdirectory: 'ios' 