on: push
name: Build Release APK and appbundle
jobs:
  build:
    name: Build Codesing App
    runs-on: ubuntu-latest
    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      STORE_FILE: ${{ github.GITHUB_ACTION_PATH }}/release.jks
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Get keystore from GitHub Secrets
      run: echo "${{ secrets.STORE_FILE }}" | base64 -d > release.jks
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle
    - name: Upload Release APK and appbundle
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          build/app/outputs/apk/release/*.apk
          build/app/outputs/bundle/release/*.aab
