on:
  push:
    branches: [main]
name: Build Release APK and appbundle
jobs:
  build:
    name: Build Codesing App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'

    - run: flutter pub get

    - name: Configure Keystore for Android
      run: |
        echo ${{ secrets.STORE_FILE }} | base64 --decode > keystore/release.jks
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        STORE_FILE: release.jks
      working-directory: android

    - run: flutter build apk --split-per-abi
    - run: flutter build appbundle

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          build/app/outputs/apk/release/*.apk
          build/app/outputs/bundle/release/*.aab