on: push
name: Build Release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    # - name: Get keystore from GitHub Secrets
    #   run: |
    #     mkdir signing
    #     echo "${{ secrets.STORE_FILE }}" | base64 -d > ./signing/release.jks
    - run: flutter build apk --release
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        STORE_FILE: echo "${{ secrets.STORE_FILE }}" | base64 -d >
    - name: Create a Release APK
      uses: actions/upload-artifact@v2
      with:
        name: APK for QA
        path: build/app/outputs/apk/release/*.apk