on:
  push:
    branches: [main]
name: Build Release APK and appbundle
jobs:
  build:
    name: Build Codesing App
    runs-on: macos-latest
    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      STORE_FILE: ../../release.jks 
      
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get

    - name: Get store file from GitHub Secrets
      run: echo "${{ secrets.STORE_FILE }}" | base64 -d > release.jks

    - run: Build Android App
    - run: flutter build apk --split-per-abi
    - run: flutter build appbundle

    - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          build/app/outputs/apk/release/*.apk
          build/app/outputs/bundle/release/*.aab
          build/ios/iphoneos/app.ipa