on: push
name: Build Release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      -run: echo "${{ GITHUB_ACTION_PATH}}"
    # env:
    #   STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    #   KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    #   KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #   STORE_FILE: ../../release.jks
    # steps:
    # - uses: actions/checkout@v1
    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: '12.x'
    # - name: Get keystore from GitHub Secrets
    #   run: echo "${{ secrets.STORE_FILE }}" | base64 -d > release.jks
    # - uses: subosito/flutter-action@v1
    #   with:
    #     flutter-version: '2.8.1'
    # - run: flutter pub get
    # - run: flutter build apk --release
    #   env:
    #     STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #     STORE_FILE: ../../release.jks
    # - run: flutter build appbundle --release
    #   env:
    #       STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    #       KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    #       KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #       STORE_FILE: ../../release.jks
    # - name: Create a Release APK
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Artifacts
    #     path: |
    #       build/app/outputs/apk/release/*.apk
    #       build/app/outputs/bundle/release/*.aab
