on:
  push:
    # tags:
    #   - '*.*.*'

name: Release

jobs:

  build:
    name: Build
    runs-on: macos-latest
    env:
      CI: ${{ secrets.CI }}
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APP_APPLE_ID: ${{ secrets.APP_APPLE_ID }}
      FASTLANE_ITC_TEAM_NAME: ${{ secrets.FASTLANE_ITC_TEAM_NAME }}
      FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
      FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
      ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}

    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.push.head.ref }}
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: '12.x'
      # - uses: subosito/flutter-action@v1
      #   with:
      #     flutter-version: '2.8.1'

      # - run: flutter pub get

      - name: Bump app version
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'bump_flutter_version'
          subdirectory: 'android'

      # - name: Build and sign Android
      #   run: | 
      #     echo "${{ secrets.STORE_FILE }}" | base64 -d > ${{ github.workspace }}/android/app/release.jks
      #     flutter build apk
      #     flutter build appbundle
      #   env:
      #     STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      #     STORE_FILE: release.jks
      
      # - name: Create play store credentials
      #   id: create-json
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "play-store-credentials.json"
      #     json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #     dir: 'android/fastlane/'

      # - name: Upload appbundle to the Google play
      #   uses: maierj/fastlane-action@v2.0.1
      #   with:
      #     lane: 'deploy'
      #     subdirectory: 'android'

      # - name: Build iOS
      #   run: |
      #     flutter build ios --release --no-codesign

      # - name: Define a basic authorization for match
      #   run: |
      #     echo "${{ secrets.ASC_AUTH_KEY }}" | base64 -d > ${{ github.workspace }}/ios/fastlane/asc-auth-key.p8
      #     echo "MATCH_GIT_BASIC_AUTHORIZATION=$(echo -n '${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}' | base64)" >> $GITHUB_ENV 
      
      # - name: Package and sign iOS
      #   uses: maierj/fastlane-action@v2.0.1
      #   with:
      #     lane: 'beta'
      #     subdirectory: 'ios'
      
      # - name: Beta ios
      #   uses: maierj/fastlane-action@v2.0.1
      #   with:
      #     lane: 'deploy'
      #     subdirectory: 'ios'

      - name: Automated commit
        run: |
          git add pubspec.yaml
          git commit -m 'Automated commit'
          git push

      # - name: Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: |
      #       build/app/outputs/apk/release/*.apk
      #       ios/build/*.ipa
      #     token: ${{ secrets.ACCESS_TOKEN }}
